# Generated by Django 4.0.6 on 2022-07-30 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted_apps', '0002_applistpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppage',
            old_name='feed_image',
            new_name='logo',
        ),
    ]
