# Generated by Django 4.0.6 on 2022-07-30 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0005_alter_svg_file'),
        ('self_hosted_apps', '0004_apppage_github_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppage',
            name='logo_svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg'),
        ),
    ]
