# Generated by Django 4.0.6 on 2022-07-30 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsvg', '0005_alter_svg_file'),
        ('self_hosted_apps', '0005_apppage_logo_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppage',
            name='date',
        ),
        migrations.AlterField(
            model_name='apppage',
            name='logo_svg',
            field=models.ForeignKey(blank=True, help_text='SVG', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailsvg.svg'),
        ),
    ]
