# Generated by Django 4.0.6 on 2022-07-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted_apps', '0006_remove_apppage_date_alter_apppage_logo_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppage',
            name='project_website',
            field=models.URLField(blank=True),
        ),
    ]
