# Generated by Django 4.0.6 on 2022-07-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted_apps', '0007_apppage_project_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppage',
            name='github_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
