version: '3.1'
services:
    caddy:
        restart: always
        container_name: caddy
        image: caddy:2-alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data/:/data
            - ./caddy_config/:/config
            - ./data/media/:/app/media

        # networks:
        #     - web

    curated:
        restart: always
        image: ghcr.io/ajfriesen/curated:latest
        # expose:
        #     - 8000
        environment:
            - url=https://curated.ajfriesen.com
            - DJANGO_MANAGEPY_MIGRATE=on
        # command:
        #     "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
        env_file:
            - .env
        depends_on:
            - curated-db
        # networks:
        #     - web

    curated-db:
        restart: always
        container_name: curated-db
        image: postgres:14.2
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        env_file:
            - .env
            # - .env.db
        # networks:
        #     - web