# Generated by Django 4.0.3 on 2022-04-05 19:06

from django.db import migrations, models
import self_hosted.models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted', '0002_app_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='pub_date',
            field=models.DateTimeField(default=self_hosted.models.default_time, verbose_name='date published'),
        ),
    ]
