# Generated by Django 4.0.3 on 2022-04-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted', '0004_tag_app_description_app_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='app',
            name='svg_logo',
            field=models.FileField(default='300x300.svg', upload_to='logos/slug'),
        ),
    ]
