# Generated by Django 4.0.3 on 2022-04-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted', '0010_alter_app_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='svg_logo',
            field=models.FileField(default='', upload_to='logos'),
        ),
    ]
