# Generated by Django 4.0.3 on 2022-06-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted', '0013_alter_app_svg_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='github_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
