# Generated by Django 4.0.3 on 2022-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted', '0014_app_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='github_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
