# Generated by Django 4.0.3 on 2022-06-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_hosted', '0015_alter_app_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='github_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
