# Generated by Django 4.0.5 on 2022-06-30 20:43

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('self_hosted', '0016_alter_app_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
