# Generated by Django 4.0.5 on 2022-07-08 10:25

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('self_hosted', '0017_app_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
